name: APK.TW Auto Checkin

on:
  schedule:
    # 每天國際標準時間 16:05 (台灣時間 00:05) 執行
    - cron: '5 16 * * *'
  workflow_dispatch: # 允許手動點擊執行測試

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 結帳程式碼
        uses: actions/checkout@v3

      - name: 設定 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安裝必要套件
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 執行簽到腳本
        env:
          # 這邊對應你之後在 Secrets 設定的名稱
          APK_COOKIE: ${{ secrets.APK_COOKIE }}
        run: python main.py
